{% set name = "types-pyaudio" %}
{% set version = "0.2.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-pyaudio-{{ version }}.tar.gz
  sha256: 34369e840dd08d7d98816d7b0a3d386b128ea02d3481b69a911c1b49d42cf832

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/pyaudio-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pyaudio
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
